version: '2'
services:
  web: 
    restart: always
    build:
      context: ./
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports: 
      - "2988:80"
   

  app:
    build:
      context: ./
      dockerfile: app.docker
    volumes:
      - ./:/var/www
   ports: 
      - "2999:80"



        